server:
  port: ${PORT:0}
spring:
  application:
    name: account-service
  devtools:
    restart:
      enabled: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}