server:
  port: ${PORT:0}
spring:
  application:
    name: account-service
  devtools:
    restart:
      enabled: false
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
    
    
    
gateway:
  ip: 192.168.0.52